### ISSUE TITLE
The deployment with ephemeral-storage limitation would work better

### ISSUE THREAD

**Issue by pacoxu** [Ottovsky/keep-open-deleted#2]
```
cat <<EOF | kubectl apply -f -
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: keepopendeleted
  name: keepopendeleted
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keepopendeleted
  template:
    metadata:
      labels:
        app: keepopendeleted
    spec:
      containers:
      - args:
        - -location
        - /tmp
        image: ottovsky/keepopendeleted
        name: keepopendeleted
        resources:
          limits:
            ephemeral-storage: 4Gi
          requests:
            ephemeral-storage: 2Gi
        volumeMounts:
        - mountPath: /tmp
          name: ephemeral
      volumes:
      - emptyDir: {}
        name: ephemeral
EOF
```
